### ISSUE TITLE
Improve publishing part

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt-community/module-template#42]
Could we explain a bit more for the https://github.com/nuxt-community/module-template#publishing part?
Also, telling the users to connect their repo on https://codecov.io/ and add a GitHub secret (Settings -> Secrets -> CODECOV_TOKEN) ?

**Comment by pi0** [comment]
I wish this process could be somehow automated same as CircleCI does for coverage...

**Comment by ricardogobbosouza** [comment]
We can use https://github.com/codecov/codecov-action#usage
