### ISSUE TITLE
Adding issue templates

### ISSUE THREAD

**Issue by Atinux** [nuxt-community/module-template#48]
It would be nice that the module could preset issue templates by default.

Thinking of:
- https://github.com/nuxt-community/nuxt-i18n/tree/master/.github/ISSUE_TEMPLATE
- https://github.com/nuxt-community/color-mode-module/tree/master/.github/ISSUE_TEMPLATE

**Comment by richardeschloss** [comment]
Can I suggest for the issue template...depending on the issue open, if it's a bug, can we have a section for animated screenshot? (and maybe that section header could have quick links that tell people how to create screen records / animated gifs ?). 

I find that helps me really see "what did the user try"

**Comment by richardeschloss** [comment]
Hi I just took a stab at this one since it was "good first issue". #49 .

**Comment by richardeschloss** [comment]
We're in just a bit of a bind.. for some reason `vue init` strips out the yaml frontmatter needed in the issue templates :(

**Comment by pi0** [comment]
@richardeschloss Thanks for the PR :heart:  Would you please rebase it [template](https://github.com/nuxt-community/module-template/tree/template) branch?

**Comment by richardeschloss** [comment]
Sure. I should have looked there first :)

**Comment by richardeschloss** [comment]
Also, would you guys be open to simply extending create-nuxt-app to create the module? It seems like you have more control over that. My process to date has been to do exactly that: create nuxt app with all the tools I like, but then tweak for modules. (That create-nuxt-app could use the github temlates)

**Comment by pi0** [comment]
#50 merged (releasing with template refactor)
