### ISSUE TITLE
[template] yarn dev not working

### ISSUE THREAD

**Issue by pi0** [nuxt-community/module-template#58]
Since using siroc, we need either CJS stub (wrapped by jiti/siroc) or `nuxt-ts` runtime for test fixture

**Comment by danielroe** [comment]
Note to self: watch template files too to trigger HMR

**Comment by danielroe** [comment]
We could fix this with a custom stub:
```js
const _require = require('jiti')(__filename)
const _default = _require('./../src/module')

module.exports = _default
```
But the question is whether this should be in `siroc` by default. @pi0 Your thoughts? (The assumption for `siroc` stubbing previously was that the stub would be consumed by a TS-capable file.)

**Comment by danielroe** [comment]
Note that this will also close #59 - as a stub will allow the jest tests to run correctly against `src`. (See #62 - this setup is working perfectly with the above stub.)

**Comment by pi0** [comment]
For tests, we will lose coverage if passing through jiti (jest likes using it's own babel transformer). Just we also then need additional `test/fixture` using src version of module. I think using CJS stub could make setup much easier...

Overall we have two possible solutions:
- CJS stub and Jest TS setup
- `nuxt-ts` and TS setup

**Comment by danielroe** [comment]
This stub fixes the coverage problem:
```js
let _default
try {
  _default = require('npm_package')
} catch {
  const _require = require('jiti')(__filename)
  _default = _require('./../src/module')
}

module.exports = _default
```

**Comment by pi0** [comment]
Hmm nice idea but it would add `moduleNameMapper` assumtion to siroc also what about packages with mutitple entrypoints? (`dist/cli`, `dist/module`)

**Comment by danielroe** [comment]
Agree. I think let's not worry about stubbing but instead use Nuxt TS.
