### ISSUE TITLE
[template] test using src

### ISSUE THREAD

**Issue by pi0** [nuxt-community/module-template#59]
We need to setup jest config to be able to test directly from src

**Comment by danielroe** [comment]
Would we always want to test against src? I can imagine it would be useful to test against built files on prerelease

**Comment by danielroe** [comment]
Would we always want to test against src? I can imagine it would be useful to test against built files on prerelease

**Comment by pi0** [comment]
@danielroe agree just we may lose coverage unless generating source maps and also making local tests harder.

(new feature idea) Maybe we can develop a custom utility to verify npm packaging? (proper files included and entrypoint require is fine on CJS env)
