### ISSUE TITLE
[template] add netlify.toml

### ISSUE THREAD

**Issue by pi0** [nuxt-community/module-template#60]
Similar to https://github.com/nuxt-community/axios-module/blob/dev/netlify.toml otherwise netlify setup needs to specify commands and docs dir. /cc @Atinux @danielroe

**Comment by Atinux** [comment]
I would ideally no choose between Netlify, Vercel of GH page honestly. But instead document it depending their hosting choice.

**Comment by danielroe** [comment]
Would we also like a `vercel.json`?

**Comment by pi0** [comment]
@Atinux I see your point. But since the template is mainly for `nuxt-community`, we may still need a prefered hosting otherwise it would be really hard to manage documentations on different places (taking i18n migration as an example)

**Comment by Atinux** [comment]
Agree, let's keep the Netlify.toml and use content instead of VuePress
