### ISSUE TITLE
[template] should we remove `husky` and `commitlint`?

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt-community/module-template#64]
These tools help with `standard-version`

**Comment by danielroe** [comment]
I would suggest using yorkie instead of husky.

**Comment by ricardogobbosouza** [comment]
`yorkie` It has not been updated for more than 2 years

**Comment by pi0** [comment]
Related to https://github.com/nuxt/nuxt.js/issues/7174#issuecomment-609067439. I think generally it is not a good practice to directly commit to master and when using PR, it is final merge message which is important. Also there are situations we won't want a change to be included in changelog. Still it is something optional and up to repo maintainer to add :)
